services:
  api:
    build:
      context: .
      target: api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - NODE_ENV=development
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ".:/app"
    command: ["npm", "run", "start  "]

  mariadb:
    image: mariadb:11.2.2
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_HOST: ${DB_HOST}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
        - ./docker/mariadb/data:/var/lib/mysql
    healthcheck:
        test: "/usr/bin/mysql --user=${DB_USER} --password=${DB_PASSWORD} --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10
        start_period: 1m

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
    mariadb_data:

