services:
  api:
    build:
      context: .
      target: api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - NODE_ENV=development
    depends_on:
      - db
    volumes:
      - ".:/usr/src/app"
    command: ["npm", "run", "start  "]

  db:
    image: mariadb:11.2.2
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_HOST: ${DB_HOST}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
        - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080

