version: '3.8'

services:
  app-prod:
    image: ghcr.io/alexispet/final-test-acestv:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.app-prod.rule=Host(`ec2-18-207-227-134.compute-1.amazonaws.com`)"
      - "traefik.http.routers.app-prod.entrypoints=web"
    volumes:
      - "./dev-data:/app/data"

  mariadb:
    image: mariadb:11.2.2
    environment:
      MARIADB_HOST: ${DB_HOST}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - "./docker/mariadb/data:/var/lib/mysql"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect" ]
      interval: 5s
      timeout: 20s
      retries: 10

networks:
  default:
    external:
      name: web
