version: '3.8'

services:
  app-dev:
    image: ghcr.io/alexispet/final-test-acestv/api:develop
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      mariadb_dev:
        condition: service_healthy
    volumes:
      - "./dev-data:/app/data"
    networks:
      - web
      - dev_network

  mariadb_dev:
    image: mariadb:11.2.2
    environment:
      MARIADB_HOST: ${DB_HOST}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - dev-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect" ]
      interval: 5s
      timeout: 20s
      retries: 10
    networks:
      - dev_network

volumes:
  dev-db:

networks:
  web:
    external: true
  dev_network:
