version: '3.8'

services:
  app-prod:
    image: ghcr.io/alexispet/final-test-acestv/api:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.app-prod.rule=Host(`ec2-54-210-166-197.compute-1.amazonaws.com`)"
      - "traefik.http.routers.app-prod.entrypoints=web"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - "./dev-data:/app/data"
    networks:
      - web
      - prod_network
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:11.2.2
    environment:
      MARIADB_HOST: ${DB_HOST}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - prod-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect" ]
      interval: 5s
      timeout: 20s
      retries: 10
    networks:
      - prod_network

volumes:
  prod-db:

networks:
  web:
    external: true
  prod_network:
