name: Lighthouse Audit

on:
  schedule:
    - cron: '5 14 * * *' # Exécute le workflow tous les jours à minuit UTC

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.5.0'


      - name: Install Lighthouse
        run: npm install -g @lhci/cli@0.7.x


      - name: Run Lighthouse Audit
        run: lhci autorun --collect.url=http://ec2-44-211-37-214.compute-1.amazonaws.com/
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
